[package]
name = "movie_log"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
matroska = "0.19.0"
polars = "0.25.1"
csv = "1.1.6"
serde = { version = "1.0.148", features = ["derive"] }