letterboxd = "https://letterboxd.com/equus497/films/"
enc_list = ["Tigole", 
    "FraMeSToR", 
    "Silence", 
    "afm72", 
    "DDR", 
    "Bandi", 
    "SAMPA", 
    "3xO", 
    "Joy", 
    "RARBG", 
    "SARTRE", 
    "PHOCiS", 
    "TERMiNAL", 
    "PSA", 
    "K1tKat", 
    "FreetheFish", 
    "Natty", 
    "IchtyFinger", 
    "BeiTai", 
    "LEGi0N",
    "alfaHD", 
    "HDH", 
    "HANDS", 
    "GREENOTEA", 
    "IWFM", 
    "FRDS", 
    "Ritaj", 
    "Enthwar", 
    "t3nzin", 
    "EDG", 
    "HDArea"
    ]